// <auto-generated />
namespace GroupUpWeb.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class correcao_signin_column_user : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(correcao_signin_column_user));
        
        string IMigrationMetadata.Id
        {
            get { return "201604101927119_correcao_signin_column_user"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
