// <auto-generated />
namespace GroupUpWeb.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class correcao_id_group : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(correcao_id_group));
        
        string IMigrationMetadata.Id
        {
            get { return "201604101923233_correcao_id_group"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
